// <auto-generated />
namespace XZMCWJZS.DDD.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_Book_20180104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Book_20180104));
        
        string IMigrationMetadata.Id
        {
            get { return "201801040850585_update_Book_20180104"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
